### ISSUE TITLE
"make install" does not work

### ISSUE THREAD

**Issue by LyndStringer** [NOAA-GSL/SENA-yppm#22]
### Issue checklist

- [x] I have read the [README](https://github.com/NOAA-GSL/SENA-yppm/blob/develop/README.md) and [ref/README](https://github.com/NOAA-GSL/SENA-yppm/blob/develop/ref/README.md), including the Troubleshooting Guide.
- [x] I have reviewed existing issues to ensure this has not already been reported.

### Describe the bug

make install not working

### Recipe to reproduce

```
$ make install
make: *** No rule to make target `install'.  Stop.
```
### Expected behavior

When "make install" worked, the executable, yppm, would be placed in ./ref/exe

**Comment by christopherwharrop-noaa** [comment]
@LyndStringer - I can reproduce.  I know what the problem is and I will issue a PR to fix soon.
