### ISSUE TITLE
Stacksize Limit

### ISSUE THREAD

**Issue by LyndStringer** [NOAA-GSL/SENA-yppm#25]
### Issue checklist

- [x] I have read the [README](https://github.com/NOAA-GSL/SENA-yppm/blob/develop/README.md) and [ref/README](https://github.com/NOAA-GSL/SENA-yppm/blob/develop/ref/README.md), including the Troubleshooting Guide.
- [x] I have reviewed existing issues to ensure this has not already been reported.

### Describe the bug

The interpolation changes to the kernel SENA-yppm is causing a stacksize overflow.

### Recipe to reproduce

On Orion: ./build.sh intel release

**Comment by christopherwharrop-noaa** [comment]
Just to clarify, this is not just an issue for Orion. Many systems have a small stacksize by default, and this issue will occur anywhere the stacksize is too small.
